### PR TITLE
enforce num_threads(nStreams) on OpenMP loops over streams on CPU/GPU

### PR DESCRIPTION
**Pull request by srlantz**
This PR fixes a potential source of errors (maybe even a bug - sorry if it was introduced in a previous PR). Given that the --default-stream per-thread option is presented to nvcc in the Makefile, it appears that the intention of the OpenMP loop over nStreams in strip-cluster.cc is to create nStreams streams on the GPU. In that case, it makes sense to have```#pragma omp parallel for``` include the clause ```num_threads(nStreams)```. Then, to have a fair timing comparison on the CPU, the same thing should be done in the CPU code section. Of course, the optimum number of streams may be different on the CPU vs. GPU; but anyway, for this PR, nStreams=8 (a power of 2) on both. That way, the 32 CPU cores on the Skylake Gold test machine can be evenly divided among streams.

A couple of other points are addressed in this PR. First, do the allocateCalibData and copying steps really need to be done on every iteration? Those statements been moved outside the loop. Also, in the CPU code, it seems incorrect to put the outer loop inside ```#pragma omp parallel```, because all OMP_NUM_THREADS threads will execute a copy of that loop, and race conditions could occur on the shared loop index iter. If the goal is to eliminate the overhead of forking parallel sections over and over, then perhaps ```#pragma omp parallel private(iter) num_threads(nStreams)``` could be placed ahead of the outer loop. But these days, OpenMP typically does not start and stop threads; it just keeps all the threads running and assigns new work to them as needed.

### CODE REVIEW

**Comment by beiwang2003** [comment]
I should be safe without private(iter). My understanding is iter is defined inside the parallel region, so will be private by default.

**Comment by srlantz** [comment]
OK, yes, I think you are right about that. But in any case, putting the ```parallel for``` inside the first loop makes the CPU code more similar to the GPU code.

In general, I suppose it does not matter too much whether all the threads execute that particular loop in parallel, or whether just the master thread does it. There may some minor difference in the amount of overhead.

**Comment by beiwang2003** [comment]
You are right. I merged the changes to master.

**Comment by srlantz** [comment]
Whoops, the GPU code actually does not work when the calls to allocateCalibDataGPU and cpyCalibDataToGPU are moved outside the first for loop. The code works fine if the two calls are moved back inside the loop. Can you see if there is a way to do those two function calls just one time, i.e., not inside the loop? Then push the fix? Or I can just put those calls back where they started.

**Comment by beiwang2003** [comment]
just fixed the bug and pushed the change. We need to move free out of the loop as well. Can you please check?

**Comment by srlantz** [comment]
Yes, this completes the fix that I had in mind. So now the memory is allocated on the GPU once, the calibration data is copied over to the GPU once, and (thanks to your bug fix) the memory is freed once at the end. I timed the code with and without these changes on lnx7188, and the "GPU Memory Transfer Host to Device Time" is reduced by 40%! Looks good to me.

**Pull request merged**
